# Generated by Django 5.1.5 on 2025-01-27 02:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_bug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Update',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Atualização',
                'verbose_name_plural': 'Atualizações',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UpdateImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='updates/', verbose_name='Imagem')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('update', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='store.update')),
            ],
            options={
                'verbose_name': 'Imagem da Atualização',
                'verbose_name_plural': 'Imagens das Atualizações',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='UpdateLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Título')),
                ('url', models.URLField(verbose_name='URL')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('update', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='store.update')),
            ],
            options={
                'verbose_name': 'Link da Atualização',
                'verbose_name_plural': 'Links das Atualizações',
                'ordering': ['created_at'],
            },
        ),
    ]
