# Generated by Django 5.1.5 on 2025-01-27 02:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_update_updateimage_updatelink'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComingSoon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('release_date', models.DateField(blank=True, null=True, verbose_name='Data de Lançamento')),
                ('status', models.CharField(default='Em Desenvolvimento', max_length=50, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Em Breve',
                'verbose_name_plural': 'Em Breve',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('date', models.DateTimeField(verbose_name='Data do Evento')),
                ('location', models.CharField(max_length=200, verbose_name='Local')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='ComingSoonImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='coming_soon/', verbose_name='Imagem')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('coming_soon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='store.comingsoon')),
            ],
            options={
                'verbose_name': 'Imagem do Em Breve',
                'verbose_name_plural': 'Imagens do Em Breve',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='EventImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='events/', verbose_name='Imagem')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='store.event')),
            ],
            options={
                'verbose_name': 'Imagem do Evento',
                'verbose_name_plural': 'Imagens dos Eventos',
                'ordering': ['created_at'],
            },
        ),
    ]
