# Generated by Django 5.1.5 on 2025-01-26 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BugReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('screenshot', models.ImageField(blank=True, null=True, upload_to='bug_reports/', verbose_name='Captura de Tela')),
                ('user_id', models.CharField(max_length=50, verbose_name='ID do Roblox')),
                ('username', models.CharField(max_length=100, verbose_name='Nome de usuário')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('resolved', 'Resolvido')], default='pending', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='Resolvido em')),
                ('resolution_notes', models.TextField(blank=True, verbose_name='Notas da Resolução')),
            ],
            options={
                'verbose_name': 'Bug Reportado',
                'verbose_name_plural': 'Bugs Reportados',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RobloxUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=50, unique=True, verbose_name='ID do Roblox')),
                ('username', models.CharField(max_length=100, verbose_name='Nome de usuário')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='Último login')),
            ],
            options={
                'verbose_name': 'Usuário do Roblox',
                'verbose_name_plural': 'Usuários do Roblox',
                'ordering': ['-created_at'],
            },
        ),
    ]
